nelmio_api_doc:
  areas:
    path_patterns: [ ^/user, ^/auth ]
  documentation:
    info:
      title: User Service
      description: User service application!
      version: 1.0.0
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: []
    tags:
      - name: "Auth"
        description: "Authentication related endpoints"
      - name: "User"
        description: "User related endpoints"