security:
    encoders:
      App\Entity\User\User:
        algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User\User
                property: email
    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
        ROLE_SUPER_BLOG_MODERATOR: [ROLE_BLOG_MODERATOR]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
